"""Package directory, zip, and open helpers."""

from __future__ import annotations

import json
import shutil
import zipfile
from dataclasses import dataclass
from pathlib import Path
from tempfile import TemporaryDirectory
from types import TracebackType

from mddatanet.format.dataset_card import write_dataset_card
from mddatanet.format.metadata import write_metadata
from mddatanet.format.provenance import write_provenance
from mddatanet.format.schema import Metadata, Provenance
from mddatanet.io.checksums import write_checksums
from mddatanet.io.zarr_store import create_numeric_vector, create_string_array, create_zarr_store
from mddatanet.utils.errors import PackageError
from mddatanet.utils.paths import (
    PACKAGE_DIR_SUFFIX,
    ensure_can_write,
    is_package_zip,
    package_stem,
    require_exists,
)


@dataclass
class PackageHandle:
    """Open package handle.

    If the input is a zip, it is unpacked to a temporary directory and cleaned up
    when the context exits. If the input is already an unpacked package directory,
    no copy is made.
    """

    source: Path
    root: Path
    _tempdir: TemporaryDirectory[str] | None = None

    def __enter__(self) -> "PackageHandle":
        return self

    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        traceback: TracebackType | None,
    ) -> None:
        if self._tempdir is not None:
            self._tempdir.cleanup()


def create_package_directory(
    output_dir: str | Path,
    *,
    metadata: Metadata,
    provenance: Provenance | None = None,
    overwrite: bool = False,
) -> Path:
    """Create the minimal unpacked package layout."""

    output_dir = ensure_can_write(output_dir, overwrite=overwrite)
    if output_dir.exists():
        shutil.rmtree(output_dir)
    output_dir.mkdir(parents=True)
    zarr_root = create_zarr_store(output_dir / "dataset.zarr", overwrite=True)
    create_numeric_vector(
        zarr_root["trajectory"],
        "frame_indices",
        list(range(metadata.system.num_frames)),
        dtype="int64",
        overwrite=True,
    )
    create_numeric_vector(
        zarr_root["trajectory"],
        "frame_times",
        [0.0] * metadata.system.num_frames,
        dtype="float64",
        overwrite=True,
    )
    create_numeric_vector(
        zarr_root["trajectory"],
        "source_frame_indices",
        list(range(metadata.system.num_frames)),
        dtype="int64",
        overwrite=True,
    )
    create_string_array(zarr_root["trajectory"], "trajectory_ids", ["trajectory_0"] * metadata.system.num_frames)
    create_string_array(zarr_root["trajectory"], "run_ids", ["run_0"] * metadata.system.num_frames)
    create_numeric_vector(
        zarr_root["topology"],
        "residue_ids",
        [0] * metadata.system.num_atoms,
        dtype="int64",
        overwrite=True,
    )
    create_string_array(zarr_root["topology"], "atom_names", [""] * metadata.system.num_atoms)
    create_string_array(zarr_root["topology"], "residue_names", [""] * metadata.system.num_atoms)
    create_string_array(zarr_root["index"], "feature_names", metadata.features.feature_names)
    create_string_array(zarr_root["index"], "event_names", metadata.labels.event_names)
    write_metadata(output_dir, metadata)
    write_provenance(output_dir, provenance or Provenance())
    write_dataset_card(output_dir, metadata, provenance)
    (output_dir / "README.md").write_text(
        f"# {metadata.dataset_name}\n\nGenerated by MDDataNet.\n",
        encoding="utf-8",
    )
    (output_dir / "LICENSE").write_text(f"{metadata.license}\n", encoding="utf-8")
    write_checksums(output_dir)
    return output_dir


def open_package(path: str | Path) -> PackageHandle:
    path = require_exists(path, label="package")
    if path.is_dir():
        return PackageHandle(source=path, root=path)
    if not is_package_zip(path):
        raise PackageError(
            f"Unsupported package path: {path}",
            suggestion="Use an unpacked .mddatanet directory or a .mddatanet.zip file.",
        )
    tempdir = TemporaryDirectory(prefix="mddatanet-open-")
    root_parent = Path(tempdir.name)
    _safe_extract(path, root_parent)
    candidates = [candidate for candidate in root_parent.iterdir() if candidate.is_dir()]
    if len(candidates) == 1:
        root = candidates[0]
    else:
        expected = root_parent / f"{package_stem(path)}{PACKAGE_DIR_SUFFIX}"
        root = expected if expected.exists() else root_parent
    return PackageHandle(source=path, root=root, _tempdir=tempdir)


def pack_package(source_dir: str | Path, output_zip: str | Path, *, overwrite: bool = False) -> Path:
    source_dir = require_exists(source_dir, label="source package directory")
    if not source_dir.is_dir():
        raise PackageError(f"Pack source must be a directory: {source_dir}")
    if not (source_dir / "dataset.zarr").exists():
        raise PackageError("Pack source is missing dataset.zarr")
    output_zip = ensure_can_write(output_zip, overwrite=overwrite)
    if output_zip.exists():
        output_zip.unlink()
    write_checksums(source_dir)
    base = source_dir.name
    with zipfile.ZipFile(output_zip, mode="w", compression=zipfile.ZIP_DEFLATED) as archive:
        for path in sorted(source_dir.rglob("*")):
            if path.is_file():
                archive.write(path, arcname=str(Path(base) / path.relative_to(source_dir)))
    return output_zip


def unpack_package(package_zip: str | Path, output_dir: str | Path, *, overwrite: bool = False) -> Path:
    package_zip = require_exists(package_zip, label="package zip")
    output_dir = ensure_can_write(output_dir, overwrite=overwrite)
    if output_dir.exists():
        shutil.rmtree(output_dir)
    output_dir.mkdir(parents=True)
    _safe_extract(package_zip, output_dir)
    return output_dir


def copy_package_to(source: str | Path, destination: str | Path, *, overwrite: bool = False) -> Path:
    with open_package(source) as handle:
        destination = ensure_can_write(destination, overwrite=overwrite)
        if destination.exists():
            shutil.rmtree(destination)
        shutil.copytree(handle.root, destination)
        return destination


def write_json(path: str | Path, data: object) -> None:
    with Path(path).open("w", encoding="utf-8") as handle:
        json.dump(data, handle, indent=2)
        handle.write("\n")


def _safe_extract(package_zip: str | Path, destination: Path) -> None:
    destination = destination.resolve()
    with zipfile.ZipFile(package_zip) as archive:
        for member in archive.infolist():
            target = (destination / member.filename).resolve()
            if destination not in target.parents and target != destination:
                raise PackageError(f"Unsafe zip member path: {member.filename}")
        archive.extractall(destination)
